### ISSUE TITLE
view_details_and_ux_updates

### ISSUE THREAD

**Issue by DevAbdoTolba** [DevAbdoTolba/Pre_AHC-Status_APP#38]
In the AdminDataGrid component

- [x] for each row add a `view` button to navigate to the URL `item/<id>` for each row has it's own id from the datagrid
- [x] disable row selection on click
- [x]  in the column important. if the row is important use this icon [PriorityHighRoundedIcon](https://mui.com/material-ui/material-icons/?query=important&theme=Rounded&selected=PriorityHighRounded) and yellow
- [x]  in the column level. set the text color of the status column value only to { easy : green; normal : yellow; hard : red;} use default MUI colors.
- [x] Add what you think It must be added and mention them 🫡

**Comment by garma-a** [comment]
This sounds great! I have already completed the first two tasks, but I have a question: What do you want to display if the row in the table is not important?

**Comment by DevAbdoTolba** [comment]
> This sounds great! I have already completed the first two tasks, but I have a question: What do you want to display if the row in the table is not important?

Nothing 👀
