### ISSUE TITLE
updating_the_values

### ISSUE THREAD

**Issue by DevAbdoTolba** [DevAbdoTolba/Pre_AHC-Status_APP#48]
create all the `update` endpoints

- [ ] `/update_status/<id>` method=PATCH body json { "status" : "open"|"close"} 
> when updating status make sure if the status is set to "close" generate a date to be set in the closeDate with its correct format and reset it to None if it was set to "open" again

- [ ] `/update_important/<id>`  method=PATCH body json {"important": true|false}

**Comment by NightMare489** [comment]
What are the data that should be updated in update_status? is it only the close and CloseDate? also is update_important a toggle ? so if it was set to important if you call that endpoint again it will be back to normal?

**Comment by DevAbdoTolba** [comment]
> What are the data that should be updated in update_status? is it only the close and CloseDate? also is update_important a toggle ? so if it was set to important if you call that endpoint again it will be back to normal?

More details are added to the issue please review
