### ISSUE TITLE
admin_data_grid_filters

### ISSUE THREAD

**Issue by DevAbdoTolba** [DevAbdoTolba/Pre_AHC-Status_APP#55]
add fetch buttons to get the following : 

- [x] view all  `/get/all`
> GET no body no headers

- [x] closed/open only view `/get/status?status=${open|close}`
> GET no body no headers ?status param
- [x] important only view `/get/important`
> GET no body no headers
- [x] easy/normal/hard view `/api/get/level?level=${easy|normal|hard}`
> GET no body no header ?level param

- [x] design of choice that fits

**Comment by garma-a** [comment]
should i keep the refresh button or remove it ?

**Comment by DevAbdoTolba** [comment]
> should i keep the refresh button or remove it ?

Convert it into `view all`
